/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocationRouteImport } from './routes/location'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsWoundCareRouteImport } from './routes/products.wound-care'
import { Route as ProductsSheepGoatsRouteImport } from './routes/products.sheep-goats'
import { Route as ProductsRabbitsRouteImport } from './routes/products.rabbits'
import { Route as ProductsPoultryRouteImport } from './routes/products.poultry'
import { Route as ProductsHorseTackRouteImport } from './routes/products.horse-tack'
import { Route as ProductsHorseCareRouteImport } from './routes/products.horse-care'
import { Route as ProductsHorseRouteImport } from './routes/products.horse'
import { Route as ProductsHardwareRouteImport } from './routes/products.hardware'
import { Route as ProductsEquipmentRouteImport } from './routes/products.equipment'
import { Route as ProductsDogsCatsRouteImport } from './routes/products.dogs-cats'
import { Route as ProductsCattleRouteImport } from './routes/products.cattle'

const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWoundCareRoute = ProductsWoundCareRouteImport.update({
  id: '/products/wound-care',
  path: '/products/wound-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSheepGoatsRoute = ProductsSheepGoatsRouteImport.update({
  id: '/products/sheep-goats',
  path: '/products/sheep-goats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRabbitsRoute = ProductsRabbitsRouteImport.update({
  id: '/products/rabbits',
  path: '/products/rabbits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPoultryRoute = ProductsPoultryRouteImport.update({
  id: '/products/poultry',
  path: '/products/poultry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHorseTackRoute = ProductsHorseTackRouteImport.update({
  id: '/products/horse-tack',
  path: '/products/horse-tack',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHorseCareRoute = ProductsHorseCareRouteImport.update({
  id: '/products/horse-care',
  path: '/products/horse-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHorseRoute = ProductsHorseRouteImport.update({
  id: '/products/horse',
  path: '/products/horse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHardwareRoute = ProductsHardwareRouteImport.update({
  id: '/products/hardware',
  path: '/products/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEquipmentRoute = ProductsEquipmentRouteImport.update({
  id: '/products/equipment',
  path: '/products/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDogsCatsRoute = ProductsDogsCatsRouteImport.update({
  id: '/products/dogs-cats',
  path: '/products/dogs-cats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCattleRoute = ProductsCattleRouteImport.update({
  id: '/products/cattle',
  path: '/products/cattle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/products/cattle': typeof ProductsCattleRoute
  '/products/dogs-cats': typeof ProductsDogsCatsRoute
  '/products/equipment': typeof ProductsEquipmentRoute
  '/products/hardware': typeof ProductsHardwareRoute
  '/products/horse': typeof ProductsHorseRoute
  '/products/horse-care': typeof ProductsHorseCareRoute
  '/products/horse-tack': typeof ProductsHorseTackRoute
  '/products/poultry': typeof ProductsPoultryRoute
  '/products/rabbits': typeof ProductsRabbitsRoute
  '/products/sheep-goats': typeof ProductsSheepGoatsRoute
  '/products/wound-care': typeof ProductsWoundCareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/products/cattle': typeof ProductsCattleRoute
  '/products/dogs-cats': typeof ProductsDogsCatsRoute
  '/products/equipment': typeof ProductsEquipmentRoute
  '/products/hardware': typeof ProductsHardwareRoute
  '/products/horse': typeof ProductsHorseRoute
  '/products/horse-care': typeof ProductsHorseCareRoute
  '/products/horse-tack': typeof ProductsHorseTackRoute
  '/products/poultry': typeof ProductsPoultryRoute
  '/products/rabbits': typeof ProductsRabbitsRoute
  '/products/sheep-goats': typeof ProductsSheepGoatsRoute
  '/products/wound-care': typeof ProductsWoundCareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/products/cattle': typeof ProductsCattleRoute
  '/products/dogs-cats': typeof ProductsDogsCatsRoute
  '/products/equipment': typeof ProductsEquipmentRoute
  '/products/hardware': typeof ProductsHardwareRoute
  '/products/horse': typeof ProductsHorseRoute
  '/products/horse-care': typeof ProductsHorseCareRoute
  '/products/horse-tack': typeof ProductsHorseTackRoute
  '/products/poultry': typeof ProductsPoultryRoute
  '/products/rabbits': typeof ProductsRabbitsRoute
  '/products/sheep-goats': typeof ProductsSheepGoatsRoute
  '/products/wound-care': typeof ProductsWoundCareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/location'
    | '/products/cattle'
    | '/products/dogs-cats'
    | '/products/equipment'
    | '/products/hardware'
    | '/products/horse'
    | '/products/horse-care'
    | '/products/horse-tack'
    | '/products/poultry'
    | '/products/rabbits'
    | '/products/sheep-goats'
    | '/products/wound-care'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/location'
    | '/products/cattle'
    | '/products/dogs-cats'
    | '/products/equipment'
    | '/products/hardware'
    | '/products/horse'
    | '/products/horse-care'
    | '/products/horse-tack'
    | '/products/poultry'
    | '/products/rabbits'
    | '/products/sheep-goats'
    | '/products/wound-care'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/location'
    | '/products/cattle'
    | '/products/dogs-cats'
    | '/products/equipment'
    | '/products/hardware'
    | '/products/horse'
    | '/products/horse-care'
    | '/products/horse-tack'
    | '/products/poultry'
    | '/products/rabbits'
    | '/products/sheep-goats'
    | '/products/wound-care'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LocationRoute: typeof LocationRoute
  ProductsCattleRoute: typeof ProductsCattleRoute
  ProductsDogsCatsRoute: typeof ProductsDogsCatsRoute
  ProductsEquipmentRoute: typeof ProductsEquipmentRoute
  ProductsHardwareRoute: typeof ProductsHardwareRoute
  ProductsHorseRoute: typeof ProductsHorseRoute
  ProductsHorseCareRoute: typeof ProductsHorseCareRoute
  ProductsHorseTackRoute: typeof ProductsHorseTackRoute
  ProductsPoultryRoute: typeof ProductsPoultryRoute
  ProductsRabbitsRoute: typeof ProductsRabbitsRoute
  ProductsSheepGoatsRoute: typeof ProductsSheepGoatsRoute
  ProductsWoundCareRoute: typeof ProductsWoundCareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/wound-care': {
      id: '/products/wound-care'
      path: '/products/wound-care'
      fullPath: '/products/wound-care'
      preLoaderRoute: typeof ProductsWoundCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/sheep-goats': {
      id: '/products/sheep-goats'
      path: '/products/sheep-goats'
      fullPath: '/products/sheep-goats'
      preLoaderRoute: typeof ProductsSheepGoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rabbits': {
      id: '/products/rabbits'
      path: '/products/rabbits'
      fullPath: '/products/rabbits'
      preLoaderRoute: typeof ProductsRabbitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/poultry': {
      id: '/products/poultry'
      path: '/products/poultry'
      fullPath: '/products/poultry'
      preLoaderRoute: typeof ProductsPoultryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/horse-tack': {
      id: '/products/horse-tack'
      path: '/products/horse-tack'
      fullPath: '/products/horse-tack'
      preLoaderRoute: typeof ProductsHorseTackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/horse-care': {
      id: '/products/horse-care'
      path: '/products/horse-care'
      fullPath: '/products/horse-care'
      preLoaderRoute: typeof ProductsHorseCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/horse': {
      id: '/products/horse'
      path: '/products/horse'
      fullPath: '/products/horse'
      preLoaderRoute: typeof ProductsHorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hardware': {
      id: '/products/hardware'
      path: '/products/hardware'
      fullPath: '/products/hardware'
      preLoaderRoute: typeof ProductsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/equipment': {
      id: '/products/equipment'
      path: '/products/equipment'
      fullPath: '/products/equipment'
      preLoaderRoute: typeof ProductsEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/dogs-cats': {
      id: '/products/dogs-cats'
      path: '/products/dogs-cats'
      fullPath: '/products/dogs-cats'
      preLoaderRoute: typeof ProductsDogsCatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cattle': {
      id: '/products/cattle'
      path: '/products/cattle'
      fullPath: '/products/cattle'
      preLoaderRoute: typeof ProductsCattleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LocationRoute: LocationRoute,
  ProductsCattleRoute: ProductsCattleRoute,
  ProductsDogsCatsRoute: ProductsDogsCatsRoute,
  ProductsEquipmentRoute: ProductsEquipmentRoute,
  ProductsHardwareRoute: ProductsHardwareRoute,
  ProductsHorseRoute: ProductsHorseRoute,
  ProductsHorseCareRoute: ProductsHorseCareRoute,
  ProductsHorseTackRoute: ProductsHorseTackRoute,
  ProductsPoultryRoute: ProductsPoultryRoute,
  ProductsRabbitsRoute: ProductsRabbitsRoute,
  ProductsSheepGoatsRoute: ProductsSheepGoatsRoute,
  ProductsWoundCareRoute: ProductsWoundCareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
